### ISSUE TITLE
DataObject Create method MIA

### ISSUE THREAD

**Issue by thumbtech** [Braunson/laravel-rackspace-cdn#7]
I'm sure this is a longshot since this is all ancient history, but on the off chance this rings a bell and saves my hide I thought I'd throw it out:

I have a site with an older Laravel 5.1 site who wants to implement Rackspace CDN so I thought I'd give it a go and all has gone well except command:

```
php artisan cdn:sync public/uploads/docs/ --trim=public
```

returns

```
[OpenCloud\Common\Exceptions\RuntimeException]
No method OpenCloud\ObjectStore\Resource\DataObject::Create()
```

I believe this stems laravel-rackspace-cdn/src/Braunson/LaravelRackspaceCdn/OpenCloud.php :

```
...
	public function createDataObject($container, $filePath, $fileName = null, $extract = null)
	{
		if(is_null($fileName)){
			$fileName = basename($filePath);
		}

		$container = $this->getContainer($container);

		$headers = array(
			"Access-Control-Allow-Origin" => "*"
		);

		$object = $container->DataObject();
=>		$object->Create(array('name'=> $fileName, 'extra_headers' => $headers), $filePath, $extract);

		return $object;
	}
```

but can't figure out where/what it was referencing from there.

**Comment by Braunson** [comment]
@thumbtech It's been so long since I worked with Rackspace.

As this packages uses the library https://github.com/rackspace/php-opencloud it may have something to do with change (i.e. the `create` method was removed from the `DataObject` class).

While I don't have a RackSpace account anymore, I'd suggest changing the version of the `php-opencloud` to 1.13.0 or older.
